version: '3'
services:
  web:
    container_name: web
    build: .
    depends_on:
      - db
    ports:
      - "5000:80"
    environment:
      MYSQL_HOSTNAME: "db"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: ""
      MYSQL_DATABASE: "php"
    volumes:
      - "./src/:/var/www/html/"
  db:
    container_name: db
    image: "mariadb:latest"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "php"
